services:
  traefik:
    container_name: traefik-server
    image: traefik:v3.0
    # command:
    #   - --api.dashboard=true
    #   - --providers.docker=true
    #   - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "443:443" # Expose HTTPS port
      - "8095:8080" # Dashboard
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro     
      - ./traefik/acme:/acme # Volume for Let's Encrypt certificates
      - ./traefik/letsencrypt:/letsencrypt
    environment:
      - CF_DNS_API_TOKEN # Example for Cloudflare DNS challenge
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Redundant here, but good practice
      - "--entrypoints.web.address=:80"
      - --entrypoints.websecure.address=:443
      - "--api.insecure=true" # Enable insecure API for dashboard (dev only)
      - "--api.dashboard=true"
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - "--certificatesresolvers.myresolver.acme.email=emcodellc@gmail.com" # Replace with your email
      # - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
      # - "--certificatesresolvers.myresolver.acme.httpchallenge=true" # Use HTTP-01 challenge (simpler if only one server)
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)" # Access dashboard at traefik.localhost
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6ewIy6MOizj6rzjsg" # Example user: admin, password: password (SHA1 hashed) - USE A SECURE METHOD IN PRODUCTION
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure" # Secure dashboard
      - "traefik.http.routers.traefik-dashboard.tls=true" # Enable TLS for dashboard


  nodeserver:
    container_name: node-server
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3111:3111"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeserver.rule=Host(`node.idraws.ng`)" # Route requests to node.idraws.ng to this service
      - "traefik.http.services.nodeserver.loadbalancer.server.port=3111"
      - "traefik.http.routers.nodeserver.entrypoints=websecure" # Route through HTTPS
      - "traefik.http.routers.nodeserver.tls=true" # Enable TLS for your app
      # - "traefik.http.routers.nodeapp.entrypoints=websecure"
      - "traefik.http.routers.nodeserver.tls.certresolver=myresolver"